### ISSUE TITLE
Avoir une page "Avis" qui liste les retours

### ISSUE THREAD

**Issue by maiwann** [lassembleuse/dinan-pcaet#24]
- Vigiliantes
- Préfecture
- Mission régionale d'autorité environnementale

Qqus citations + liens pdf

**Comment by maiwann** [comment]
# Vous pouvez retrouver sur cette page les différents avis qui nous ont été communiqués autour du Plan Climat 

## Les Vigiliantes (xx septembre)

## Direction départementale des Territoires et de la Mer des Côtes-d'Armor 

> Concernant la production d'Énergies renouvelables, vous vous êtes fixé, pour 2030, un objectif de production de 334,8 GWh, soit environ 21% de la consommation finale du territoire. Cet objectif est inférieur à celui prévu par la loi Énergie-Climat qui fixe une part de 33% au moins en 2030.

> Concernant les émissions de GES, il faut souligner l'effort particulièrement important sur les GES d'origine agricole pour lequel l'objectif que vous vous êtes fixé est nettement supérieur à celui retenu au niveau national.

> (…) les fiches-actions sont relativement exhaustives. Néanmoins, elles pourraient être complétées en mentionnant les moyens humains associés à chaque action.

> Par ailleurs, et même si la réglementation prévoit une mise à jour du PCAET tous les six ans, le choix retenu de mentionner dans chaque fiche-action des échéances maximales fixées en 2027 nécessiterait d'être expliqué.

> Les modalités de gouvernance du PCAET (…) mériteraient d'être précisées en définissant notamment les moyens humains associés, leur positionnement au niveau de la collectivité ou encore les modalités de communication à destination des citoyens.

**Comment by maiwann** [comment]
😱 J'ai c/c beaucoup trop de choses de l'MRAE !! je me suis grave emballée

**Comment by clairezed** [comment]
ah oui je vais peut-être écrémer un peu :grimacing:
