### ISSUE TITLE
Communiqué de presse

### ISSUE THREAD

**Issue by clairezed** [lassembleuse/dinan-pcaet#6]

**Comment by clairezed** [comment]
Alors que la Bretagne, comme le reste de la France, sort d’un été caniculaire qui laisse les nappes phréatiques plus vides que jamais, et fait planer sur la fin d’année des risques de coupures d’eau et d’électricité, Dinan Agglomération propose à la consultation du public son Plan Climat Air Energie Territoriale.

Nous, habitantes et habitants inquiets des défis à relever, fondions beaucoup d’espoirs sur ce document, qui définit la stratégie de lutte contre le changement climatique sur notre territoire pour les 6 prochaines d’années.

Malheureusement, nous considérons que l'ambition n'y est pas.

## Un plan qui n'est pas à la hauteur des enjeux

A force de se renseigner et de s'informer et en nous appuyant sur les avis rendus par les autorités environnementales, nous identifions des points sur lesquelles les actions de l'agglomération ne sont pas à la hauteur : crédibilité des indicateurs, sobriété, implication des habitantes et habitants de l'agglomération... 

En pointant ces lacunes, nous voulons contribuer à améliorer le PCAET. 

## Faire en sorte qu'habitantes et habitants de l'agglomération puissent se saisir du plan climat

Notre ambition est de mettre le PCAET sur le devant de la scène et faciliter la consultation publique, bien que les délais soient très courts. 

Pour cela, nous lançons un site, https://plan-climat.vigiliantes.fr, qui reprend, commente et analyse les actions prévues dans le PCAET. Avec ce site, nous souhaitons

**Comment by thom4parisot** [comment]
```diff
- La recherche s'accorde
+ La recherche scientifique s'accorde depuis des décénies
```

```diff
- Face à ces enjeux considérables, nous considérons que
+ Nous considérons que
```

```diff
- consultation publique, bien que les délais soient très courts (1 mois de consultation, le minimum légal).
+ consultation publique. Et ce, alors que l'Agglomération s'économie des efforts en imposant le délai le plus court possible (1 mois de consultation, le minimum légal). C'est sans compter sur une communication réduite à peau de chagrin.
```

```diff
- Pour cela, nous lançons un site, [plan-climat.vigiliantes.fr](https://plan-climat.vigiliantes.fr/), qui reprend, commente et analyse les actions prévues dans le PCAET.
+ Nous lançons un site [**plan-climat.vigiliantes.fr**](https://plan-climat.vigiliantes.fr/). Il reprend, commente, analyse et bonifie les "actions" prévues par l'Agglomération.
```

```diff
- Enfin, nous organisons en fin de mois deux ateliers ouverts au public, dans l'idée de partager la connaissance autour du PCAET et permettre aux personnes participantes de se forger leur opinion : vendredi 23 septembre, 18h30 et dimanche 25 septembre, 14h30, salle Enki Damona à la Maison des associations.
+ Nous vous invitons à deux ateliers ouverts au public pour faire ce travail ensemble. Partageons connaissances, craintes et espoirs autour du plan climat de l'Agglomération. Venez vous forger votre opinion : **vendredi 23 septembre** à 18h30 et **dimanche 25 septembre**, 14h30, salle Enki Damona à la Maison des associations ([5bis Rue Gambetta, 22100 Dinan](https://goo.gl/maps/saQoZ37BgGwixMiF9)).
```

**Comment by clairezed** [comment]
Je vais reprendre une partie des suggestions de @thom4parisot, mais pas tout (y'a des trucs qui pourraient intégrer le site mais que je trouve un poil trop rentre dedans pour un communiqué de presse).

**Comment by clairezed** [comment]
Ou sur des invitations à l'atelier, d'ailleurs 🤔
